# Generated by Django 5.2.5 on 2025-12-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(db_column='Equipment_ID', primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(db_column='Equipment_Name', max_length=100)),
                ('type', models.CharField(db_column='Type', max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In_Use', 'In Use'), ('Under_Maintenance', 'Under Maintenance'), ('Damaged', 'Damaged')], db_column='Status', default='Available', max_length=20)),
                ('total_quantity', models.PositiveIntegerField(db_column='Total_Quantity')),
            ],
            options={
                'db_table': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(db_column='Facility_ID', primary_key=True, serialize=False)),
                ('facility_name', models.CharField(db_column='Facility_Name', max_length=100)),
                ('type', models.CharField(db_column='Type', max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Under_Maintenance', 'Under Maintenance'), ('Unavailable', 'Unavailable')], db_column='Status', default='Available', max_length=20)),
                ('capacity', models.PositiveIntegerField(db_column='Capacity')),
                ('building', models.CharField(db_column='Building', max_length=50)),
                ('floor', models.SmallIntegerField(db_column='Floor')),
                ('room_number', models.CharField(db_column='Room_Number', max_length=20)),
            ],
            options={
                'db_table': 'Facility',
            },
        ),
        migrations.CreateModel(
            name='Visitor_Application',
            fields=[
                ('application_id', models.AutoField(db_column='Application_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First_Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=50)),
                ('ic_number', models.CharField(db_column='IC_Number', max_length=20, unique=True)),
                ('application_date', models.DateField(db_column='Application_Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='Status', default='Pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, db_column='Approval_Date', null=True)),
                ('reject_reason', models.TextField(blank=True, db_column='Reject_Reason', null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='Approved_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to='accounts.staff')),
                ('created_member', models.ForeignKey(blank=True, db_column='Created_Member_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_application', to='accounts.member')),
            ],
            options={
                'db_table': 'Visitor_Application',
            },
        ),
        migrations.CreateModel(
            name='Visitor_Application_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(db_column='Email_Address', max_length=100)),
                ('application', models.ForeignKey(db_column='Application_ID', on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='management_portal.visitor_application')),
            ],
            options={
                'db_table': 'Visitor_Application_Email',
            },
        ),
        migrations.CreateModel(
            name='Visitor_Application_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=20)),
                ('application', models.ForeignKey(db_column='Application_ID', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='management_portal.visitor_application')),
            ],
            options={
                'db_table': 'Visitor_Application_Phone',
            },
        ),
        migrations.CreateModel(
            name='VisitorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('visit_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_member_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_visitor', to='management_portal.visitorapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(db_column='Maintenance_ID', primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_column='Scheduled_Date')),
                ('completion_date', models.DateField(blank=True, db_column='Completion_Date', null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='Status', max_length=20)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('equipment', models.ForeignKey(blank=True, db_column='Equipment_ID', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_records', to='management_portal.equipment')),
                ('facility', models.ForeignKey(blank=True, db_column='Facility_ID', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_records', to='management_portal.facility')),
            ],
            options={
                'db_table': 'Maintenance',
                'indexes': [models.Index(fields=['facility', 'scheduled_date'], name='Maintenance_Facilit_592806_idx'), models.Index(fields=['equipment', 'scheduled_date'], name='Maintenance_Equipme_659f45_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='visitor_application',
            index=models.Index(fields=['status', 'application_date'], name='Visitor_App_Status_31483d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitor_application_email',
            unique_together={('application', 'email_address')},
        ),
        migrations.AlterUniqueTogether(
            name='visitor_application_phone',
            unique_together={('application', 'phone_number')},
        ),
    ]
