# Generated by Django 4.2.10 on 2025-12-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorapplication',
            name='reviewed_by',
        ),
        migrations.DeleteModel(
            name='ExternalVisitor',
        ),
        migrations.DeleteModel(
            name='VisitorApplication',
        ),
    ]
