# Generated by Django 5.2.5 on 2025-12-02 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach_id', models.CharField(max_length=20, unique=True, verbose_name='教练编号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='擅长项目')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.CharField(max_length=20, unique=True, verbose_name='会员编号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('affiliation', models.CharField(blank=True, max_length=100, verbose_name='隶属单位')),
                ('membership_type', models.CharField(blank=True, max_length=50, verbose_name='会员类型')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('active', '已激活')], default='pending', max_length=20, verbose_name='状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
