# Generated by Django 5.2.5 on 2025-12-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(db_column='Member_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First_Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=50)),
                ('registration_date', models.DateField(db_column='Registration_Date')),
                ('membership_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending_Approval', 'Pending Approval')], db_column='Membership_Status', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(db_column='Coach_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First_Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=50)),
                ('sport_type', models.CharField(db_column='Sport_Type', max_length=50)),
                ('level', models.CharField(db_column='Level', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Coach',
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach_id', models.CharField(max_length=20, unique=True, verbose_name='Coach ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Specialty')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='External_Visitor',
            fields=[
                ('member', models.OneToOneField(db_column='Member_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='external_visitor_profile', serialize=False, to='accounts.member')),
                ('ic_number', models.CharField(db_column='IC_Number', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'External_Visitor',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('member', models.OneToOneField(db_column='Member_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_profile', serialize=False, to='accounts.member')),
                ('staff_id', models.CharField(db_column='Staff_ID', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('member', models.OneToOneField(db_column='Member_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to='accounts.member')),
                ('student_id', models.CharField(db_column='Student_ID', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.CharField(max_length=20, unique=True, verbose_name='Member ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('affiliation', models.CharField(blank=True, max_length=100, verbose_name='Affiliation')),
                ('membership_type', models.CharField(blank=True, max_length=50, verbose_name='Membership Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=20, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coach_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(db_column='Email_Address', max_length=100)),
                ('coach', models.ForeignKey(db_column='Coach_ID', on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='accounts.coach')),
            ],
            options={
                'db_table': 'Coach_Email',
                'unique_together': {('coach', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='Coach_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=20)),
                ('coach', models.ForeignKey(db_column='Coach_ID', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.coach')),
            ],
            options={
                'db_table': 'Coach_Phone',
                'unique_together': {('coach', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Member_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(db_column='Email_Address', max_length=100)),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='accounts.member')),
            ],
            options={
                'db_table': 'Member_Email',
                'unique_together': {('member', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='Member_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=20)),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.member')),
            ],
            options={
                'db_table': 'Member_Phone',
                'unique_together': {('member', 'phone_number')},
            },
        ),
    ]
