# Generated by Django 4.2.10 on 2025-12-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_oldreservation_assigned_officer_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoachProfile',
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
    ]
