# Generated by Django 5.2.5 on 2025-12-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('management_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(db_column='Reservation_ID', primary_key=True, serialize=False)),
                ('reservation_date', models.DateField(db_column='Reservation_Date')),
                ('start_time', models.TimeField(db_column='Start_Time')),
                ('end_time', models.TimeField(db_column='End_Time')),
                ('facility', models.ForeignKey(db_column='Facility_ID', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='management_portal.facility')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='OldBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start', models.DateTimeField()),
                ('requested_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management_portal.facility')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_bookings', to='accounts.memberprofile')),
            ],
            options={
                'db_table': 'old_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OldReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assigned_reservations', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_reservations', to='bookings.oldbooking')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management_portal.facility')),
            ],
            options={
                'db_table': 'old_reservation',
            },
        ),
        migrations.CreateModel(
            name='OldTrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('description', models.TextField(blank=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_sessions', to='accounts.coachprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management_portal.facility')),
            ],
            options={
                'db_table': 'old_training_session',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation_Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='Quantity')),
                ('equipment', models.ForeignKey(db_column='Equipment_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='management_portal.equipment')),
                ('reservation', models.ForeignKey(db_column='Reservation_ID', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='bookings.reservation')),
            ],
            options={
                'db_table': 'Reservation_Equipments',
            },
        ),
        migrations.CreateModel(
            name='ReservationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management_portal.equipment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_equipments', to='bookings.oldreservation')),
            ],
        ),
        migrations.CreateModel(
            name='SessionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_enrollments', to='accounts.memberprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_enrollments', to='bookings.oldtrainingsession')),
            ],
            options={
                'db_table': 'old_session_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('reservation', models.OneToOneField(db_column='Reservation_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='booking', serialize=False, to='bookings.reservation')),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], db_column='Booking_Status', max_length=20)),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.member')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('reservation', models.OneToOneField(db_column='Reservation_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='training_session', serialize=False, to='bookings.reservation')),
                ('max_capacity', models.PositiveIntegerField(db_column='Max_Capacity')),
                ('coach', models.ForeignKey(db_column='Coach_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='training_sessions', to='accounts.coach')),
            ],
            options={
                'db_table': 'Training_Session',
            },
        ),
        migrations.CreateModel(
            name='Session_Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(db_column='Member_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='session_enrollments', to='accounts.member')),
                ('training_session', models.ForeignKey(db_column='Reservation_ID', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='bookings.trainingsession')),
            ],
            options={
                'db_table': 'Session_Enrollment',
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['facility', 'reservation_date'], name='Reservation_Facilit_e090a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='chk_reservation_time'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('facility', 'reservation_date', 'start_time')},
        ),
        migrations.AddConstraint(
            model_name='reservation_equipments',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='chk_re_quantity'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation_equipments',
            unique_together={('reservation', 'equipment')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionenrollment',
            unique_together={('session', 'member')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['member'], name='Booking_Member__138c47_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['coach'], name='Training_Se_Coach_I_403339_idx'),
        ),
        migrations.AddIndex(
            model_name='session_enrollment',
            index=models.Index(fields=['member'], name='Session_Enr_Member__38750d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session_enrollment',
            unique_together={('training_session', 'member')},
        ),
    ]
