# Generated by Django 4.2.10 on 2025-12-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldreservation',
            name='assigned_officer',
        ),
        migrations.RemoveField(
            model_name='oldreservation',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='oldreservation',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='oldtrainingsession',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='oldtrainingsession',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='reservationequipment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='reservationequipment',
            name='reservation',
        ),
        migrations.AlterUniqueTogether(
            name='sessionenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessionenrollment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='sessionenrollment',
            name='session',
        ),
        migrations.DeleteModel(
            name='OldBooking',
        ),
        migrations.DeleteModel(
            name='OldReservation',
        ),
        migrations.DeleteModel(
            name='OldTrainingSession',
        ),
        migrations.DeleteModel(
            name='ReservationEquipment',
        ),
        migrations.DeleteModel(
            name='SessionEnrollment',
        ),
    ]
